import { Inter } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "S Maity App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en" className="p-6">
            <body className={inter.className}>
                <nav>
                    <ul className="flex gap-6">
                        <li>
                            <Link href="/">Home</Link>
                        </li>
                        <li>
                            <Link href="/courses">Courses</Link>
                        </li>
                        <li>
                            <Link href="/buttonDemo">ButtonDemo</Link>
                        </li>
                        <li>
                            <Link href="/buttonDemo2">ButtonDemo2</Link>
                        </li>
                        <li>
                            <Link href="/datafetching">Data-Fetching</Link>
                        </li>
                        <li>
                            <Link href="/allDataFetch">AllDataFetch</Link>
                        </li>
                        <li>
                            <Link href="/ReadLocalJson">ReadLocalJson</Link>
                        </li>
                        <li>
                            <Link href="/fileupload">FileUpload</Link>
                        </li>
                        <li>
                            <Link href="/WASM">C-WASM</Link>
                        </li>
                        <li>
                            <Link href="/Download">Download</Link>
                        </li>
                    </ul>
                </nav>
                <hr />
                {children}
            </body>
        </html>
    );
}
